<?php
function cabecera(string $titulo, array $u, string $modulo='', bool $mostrarSalida=true): void { ?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($titulo) ?> · Ejecuttrans</title><link rel="icon" href="/Assets/icons/icon-192x192.png"><link rel="manifest" href="/manifest.json"><meta name="theme-color" content="#2563eb"><script src="https://cdn.tailwindcss.com"></script><script>tailwind.config={corePlugins:{preflight:false}};</script><link rel="stylesheet" href="/Assets/css/app.css"><link rel="stylesheet" href="/Assets/css/layout.css"></head>
<body><div class="shell <?= $u['rol']==='conductor' ? 'driver-shell' : 'admin-shell' ?>">
<?php if ($u['rol']!=='conductor'): ?>
<aside class="sidebar" id="sidebar" aria-label="Navegación principal"><div class="sidebar-head"><a class="brand" href="/Web/admin/dashboard.php"><img src="/Assets/images/logo-ejecuttrans.png" alt=""><span>EJECUTTRANS<small>Control de recorridos</small></span></a><button type="button" class="sidebar-close" id="sidebarClose" aria-label="Cerrar menú">×</button></div><span class="nav-label">ADMINISTRACIÓN</span><nav>
<?php foreach(['dashboard'=>'Dashboard','recorridos'=>'Recorridos','buses'=>'Buses / discos','rutas'=>'Rutas','usuarios'=>'Usuarios'] as $key=>$label): if($key==='usuarios' && $u['rol']!=='admin') continue; ?><a class="<?= $modulo===$key?'selected':'' ?>" <?= $modulo===$key?'aria-current="page"':'' ?> href="/Web/admin/<?= $key ?>.php"><?= e($label) ?></a><?php endforeach ?>
<?php if($u['rol']==='admin'): ?><a href="/App/conductor/dashboard.php">App de recorridos ↗</a><?php endif ?></nav><div class="sidebar-foot">Operación · Ecuador<br><small>America/Guayaquil · UTC−5</small></div></aside>
<button class="sidebar-backdrop" id="sidebarBackdrop" type="button" aria-label="Cerrar menú" hidden></button>
<?php endif ?>
<div class="workspace"><header class="topbar"><div class="topbar-start"><?php if($u['rol']!=='conductor'): ?><button type="button" class="sidebar-toggle" id="sidebarToggle" aria-controls="sidebar" aria-expanded="true" aria-label="Ocultar menú"><span class="hamburger-lines" aria-hidden="true"><i></i><i></i><i></i></span></button><?php endif ?><span><?= $u['rol']==='conductor'?'EJECUTTRANS · CONDUCTOR':'Panel de operación' ?></span></div><div class="user-menu"><a class="user-link" href="/App/conductor/perfil.php"><?= e($u['nombres']) ?></a><span class="badge"><?= e($u['rol']) ?></span><?php if($mostrarSalida): ?><a class="logout-link" href="/auth/logout.php"><span aria-hidden="true">↪</span> Salir</a><?php endif ?></div></header><main class="content"><div class="page-heading"><div><p class="eyebrow">CONTROL DE RECORRIDOS</p><h1><?= e($titulo) ?></h1></div><span class="date"><?= date('d/m/Y') ?></span></div>
<?php }
function pie(): void { ?></main><footer>Ejecuttrans · Registro de kilometraje</footer></div></div><script src="/Assets/js/common.js"></script><script src="/Assets/js/sidebar.js"></script></body></html><?php }
